name: Bump Homebrew formula

on:
  push:
    tags: '*'

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: macos-latest
    steps:
      - uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{secrets.Token}}
          tap: pythonswiftlink/homebrew-SwiftonizeExec
          formula: SwiftonizeExec
