name: Homebrew Builder
on:
  push:
   tags:
     - '*'
  workflow_dispatch:

jobs:
  release-osx:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Build Release
      run: |
          swift build -c release --disable-sandbox --arch arm64 --arch x86_64
          mkdir release
          cp -rf .build/apple/Products/Release/SwiftonizeExecutable release/Swiftonize
          cp -rf python_stdlib release/python_stdlib
          cp -rf python-extra release/python-extra
          tar -C ./release/ -czvf ./swiftonize.tar.gz ./

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "swiftonize.tar.gz"
        token: ${{ secrets.Homebrew }}
        allowUpdates: true
