name: Bump Homebrew formula

on:
  push:
    tags: '*'
  workflow_dispatch:
  
jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{ secrets.HOMEBREW_TOKEN }}
          tap: PythonSwiftLink/homebrew-SwiftonizeExec
          #formula: swiftonizeexec
