name: Bump Homebrew formula

on:
  push:
    tags: '*'
  workflow_dispatch:
  
jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: macos-latest
    steps:
      - name: Extract version
        id: extract-version
        run: |
          echo "tag-name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - uses: mislav/bump-homebrew-formula-action@v3
        if: ${{ !contains(github.ref, '-') }} # skip prereleases
        with:
          formula-name: swiftonizeexec
          formula-path: swiftonizeexec.rb
          homebrew-tap: PythonSwiftLink/homebrew-SwiftonizeExec
          base-branch: master
          download-url: https://github.com/PythonSwiftLink/${{ steps.extract-version.outputs.tag-name }}.tar.gz
          commit-message: |
            {{formulaName}} {{version}}

            Created by https://github.com/mislav/bump-homebrew-formula-action
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
