name: Homebrew Builder
on:
  push:
   tags:
     - '*'
  workflow_dispatch:

jobs:
  release-osx:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Build Release
      run: |
          swift build -c release --disable-sandbox --arch arm64 --arch x86_64
          mkdir release
          cp -rf .build/apple/Products/Release/SwiftonizeExecutable release/Swiftonize
          cp -rf python_stdlib release/python_stdlib
          cp -rf python-extra release/python-extra
          tar -C ./release/ -czvf ./swiftonize.tar.gz ./
          
    - name: Get version
      id: get_version
      run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
    
    - name: Set SHA
      id: shasum
      run: |
        echo ::set-output name=sha::"$(shasum -a 256 ./swiftonize.tar.gz | awk '{printf $1}')"
    
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "swiftonize.tar.gz"
        token: ${{ secrets.Homebrew }}
        allowUpdates: true
    
    
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.Homebrew }}
        event-type: formula_update
        client-payload: '{"ref": "${{ steps.get_version.outputs.version }}", "sha": "${{ steps.shasum.outputs.sha }}"}'
