name: Bump Homebrew formula

on:
  push:
    tags: '*'
  workflow_dispatch:
  
jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: macos-latest
    steps:
      - uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{ secrets.HOMEBREW_TOKEN }}
          tap: PythonSwiftLink/homebrew-SwiftonizeExec
          formula: swiftonizeexec
          tag: ${{github.ref}}
          # Optional, will be determined automatically
          #url: https://github.com/PythonSwiftLink/SwiftonizeExec/archive/refs/tags/${{github.ref}}.zip
          revision: ${{github.sha}}
          livecheck: true
