name: Repository Dispatch
on:
  repository_dispatch:
    types: [homebrew_formula]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.Homebrew }}
        with:
          source-directory: 'homebrew_formula'
          destination-github-username: 'pythonswiftlink'
          destination-repository-name: 'wiki'
          user-email: pythonswiftlink@gmail.com
          target-branch: master
